change: add description at top of the script

diff --git a/improve b/improve
--- a/improve
+++ b/improve
@@ -1,15 +1,20 @@
 #!/bin/bash
+# ---------------------------------------------------------------------------- #
+#    Script made by hengtseChou
+#    Utilize OpenAI API to improve writing
+#    Should work with any language input by the user
+# ---------------------------------------------------------------------------- #
 _convert_to_single_line() {
-    local raw_input="$1"
-    local single_line="${raw_input//$'\n'/\\n}"
-    echo "$single_line"
+  local raw_input="$1"
+  local single_line="${raw_input//$'\n'/\\n}"
+  echo "$single_line"
 }
 
 if [ ! -f $HOME/bin/.improve-api-key ]; then
-	echo "Error: .improve-api-key not found."
-	exit 1
+  echo "Error: .improve-api-key not found."
+  exit 1
 else
-	api_key=$(cat $HOME/bin/.improve-api-key)
+  api_key=$(cat $HOME/bin/.improve-api-key)
 fi
 
 prompt="I want you to act as a professional content improver. I will give you a sentence or a paragraph in any language and you will detect the language, understand the context of my text and improve it in the given language. Optimize the provided text to make it more concise, clear, and engaging while retaining its original meaning. Focus on enhancing readability, removing redundancies, and improving flow. Your goal is to create a polished version that captivates the reader's attention. Responed only with the improved text."
@@ -31,5 +36,5 @@ curl -s https://api.openai.com/v1/chat/completions \
         "content": "'"$content"'"
       }
     ]
-  }' | \
+  }' |
   python3 -c "import json, sys; resp = json.load(sys.stdin); print(f'Error: {resp['error']['message']}' if 'error' in resp.keys() else resp['choices'][0]['message']['content'])"
diff --git a/lc-daily b/lc-daily
--- a/lc-daily
+++ b/lc-daily
@@ -1,11 +1,28 @@
 #!/bin/bash
-set -e
+# ---------------------------------------------------------------------------- #
+#    Script made by hengtseChou
+#    Create a new LeetCode POTD python solution file via alfa-leetcode-api
+#    User should modify the directory based on their own setup
+# ---------------------------------------------------------------------------- #
+solution_dir="$HOME/GitHub/LeetCode"
+
+if ! command -v docker &>/dev/null; then
+  echo "Error: docker is not installed."
+  exit 1
+fi
+if ! command -v jq &>/dev/null; then
+  echo "Error: jq is not installed."
+  exit 1
+fi
+if ! docker container ls -a --format '{{.Names}}' | grep -q '^alfa-leetcode-api$'; then
+  docker container create --name alfa-leetcode-api -p 3000:3000 alfaarghya/alfa-leetcode-api:2.0.1
+fi
 echo "Starting alfa-leetcode-api server..."
-docker start alfa-leetcode-api > /dev/null
+docker start alfa-leetcode-api >/dev/null
 
 echo "Fetching data from http://localhost:3000/daily..."
 
-daily=$(curl -s --retry 5 --retry-all-errors --retry-delay 1 http://localhost:3000/daily)
+daily=$(curl -s --retry 10 --retry-all-errors --retry-delay 1 http://localhost:3000/daily)
 
 titleSlug=$(echo "$daily" | jq -r '.titleSlug')
 questionFrontendId=$(echo "$daily" | jq -r '.questionFrontendId')
@@ -13,12 +30,12 @@ questionFrontendId=$(printf "%04d" $questionFrontendId)
 filename="$questionFrontendId-$titleSlug"
 
 echo "Completed. Shutting down alfa-leetcode-api server..."
-docker stop alfa-leetcode-api > /dev/null
+docker stop alfa-leetcode-api >/dev/null
 
-cd $HOME/GitHub/LeetCode/daily
+cd "$leetcode_dir/daily"
 if [ -e "$filename.py" ]; then
-    echo "The file "$filename.py" already existed. Exiting"
-    exit 1
+  echo "The file "$filename.py" already existed. Exiting"
+  exit 1
 fi
 touch "$filename.py"
 nano "$filename.py"
@@ -29,7 +46,6 @@ if [ ! -s "$filename.py" ]; then
   exit 1
 fi
 
-# black "$filename.py" -l 100 -q
 git add "$filename.py"
 git commit -m "add: daily question $(date +%F)"
 git push
diff --git a/pyclean b/pyclean
--- a/pyclean
+++ b/pyclean
@@ -1,22 +1,39 @@
 #!/bin/bash
-pycache_dirs=$(fd -H --type d "__pycache__" --exclude="*pyenv*" --exclude="*pipx*" --exclude="*Trash*")
-python_history_files=$(fd -H --type f "python_history" --exclude="*Trash*")
+# ---------------------------------------------------------------------------- #
+#    Script made by hengtseChou
+#    Clean up __pycache__ directories and .python_history files
+#    Recursively from the current directory
+# ---------------------------------------------------------------------------- #
+if ! command -v fd &>/dev/null; then
+  echo "Error: fd is not installed."
+  exit 1
+fi
 
+set -e
+use_trash=false
+if command -v trash &>/dev/null; then
+  use_trash=true
+fi
+
+pycache_dirs=$(fd -H --type d "__pycache__" --exclude="pyenv" --exclude="pipx" --exclude="Trash")
+python_history_files=$(fd -H --type f "python_history" --exclude="Trash")
 if [ -z "$pycache_dirs" ] && [ -z "$python_history_files" ]; then
   echo "No __pycache__ directories or .python_history files found."
   exit 0
 fi
-
 if [ -n "$pycache_dirs" ]; then
   echo "The following __pycache__ directories were found:"
-  echo "$pycache_dirs" | tr ' ' '\n'
+  while IFS= read -r dir; do
+    echo "  - $PWD/$dir"
+  done <<<"$pycache_dirs"
 else
   echo "No __pycache__ directories found."
 fi
-
 if [ -n "$python_history_files" ]; then
   echo "The following .python_history files were found:"
-  echo "$python_history_files" | tr ' ' '\n'
+  while IFS= read -r file; do
+    echo "  - $PWD/$file"
+  done <<<"$python_history_files"
 else
   echo "No .python_history files found."
 fi
@@ -27,24 +44,38 @@ confirm=${confirm:-yes}
 if [ "$confirm" == "yes" ]; then
   if [ -n "$pycache_dirs" ]; then
     echo "$pycache_dirs" | while read -r dir; do
-      if trash "$dir"; then
-        echo "Deleted: $dir"
+      if $use_trash; then
+        if trash "$dir"; then
+          echo "Deleted: $dir"
+        else
+          echo "Failed to delete: $dir"
+        fi
       else
-        echo "Failed to delete: $dir"
+        if rm -rf "$dir"; then
+          echo "Removed: $dir"
+        else
+          echo "Failed to reomve: $dir"
+        fi
       fi
     done
   fi
-
   if [ -n "$python_history_files" ]; then
     echo "$python_history_files" | while read -r file; do
-      if trash "$file"; then
-        echo "Deleted: $file"
+      if $use_trash; then
+        if trash "$file"; then
+          echo "Deleted: $file"
+        else
+          echo "Failed to delete: $file"
+        fi
       else
-        echo "Failed to delete: $file"
+        if rm -f "$file"; then
+          echo "Removed: $file"
+        else
+          echo "Failed to remove: $file"
+        fi
       fi
     done
   fi
 else
   echo "Deletion aborted."
 fi
-
diff --git a/rclean b/rclean
--- a/rclean
+++ b/rclean
@@ -1,31 +1,47 @@
 #!/bin/bash
-# Find all .Rhistory and .RData files excluding $HOME/.pyenv and its subdirectories
-files_to_delete=$(fd -H --type f "(Rhistory|RData)")
+# ---------------------------------------------------------------------------- #
+#    Script made by hengtseChou
+#    Clean up .Rhistory and .RData files
+#    Recursively from the current directory
+# ---------------------------------------------------------------------------- #
+if ! command -v fd &>/dev/null; then
+  echo "Error: fd is not installed."
+  exit 1
+fi
 
-# Check if any .Rhistory or .RData files were found
+set -e
+use_trash=false
+if command -v trash &>/dev/null; then
+  use_trash=true
+fi
+
+files_to_delete=$(fd -H --type f "(Rhistory|RData)" --exclude "Trash" --exclude "R" --exclude "Telegram")
 if [ -z "$files_to_delete" ]; then
   echo "No .Rhistory or .RData files found."
   exit 0
 fi
-
-# List the found .Rhistory and .RData files, each on a new line
 echo "The following .Rhistory and .RData files were found:"
-echo "$files_to_delete" | tr ' ' '\n'
+while IFS= read -r file; do
+  echo "  - $file"
+done <<<"$files_to_delete"
 
-# Prompt the user for confirmation to delete the files, default to yes
 read -p "Do you want to delete all of these files? (yes/no) [yes]: " confirm
-
-# Default to 'yes' if the user presses Enter
 confirm=${confirm:-yes}
 
-# If the user confirms, proceed with deletion
 if [ "$confirm" == "yes" ]; then
-  # Delete .Rhistory and .RData files
   echo "$files_to_delete" | while read -r file; do
-    if trash "$file"; then
-      echo "Deleted: $file"
+    if $use_trash; then
+      if trash "$file"; then
+        echo "Deleted: $file"
+      else
+        echo "Failed to delete: $file"
+      fi
     else
-      echo "Failed to delete: $file"
+      if rm -f "$file"; then
+        echo "Removed: $file"
+      else
+        echo "Failed to remove: $file"
+      fi
     fi
   done
 else
diff --git a/symlink b/symlink
--- a/symlink
+++ b/symlink
@@ -1,7 +1,11 @@
 #!/bin/bash
-
+# ---------------------------------------------------------------------------- #
+#    Script made by hengtseChou
+#    Symlink dotfiles to ~/ or ~/.config
+#    Also support custom directory
+# ---------------------------------------------------------------------------- #
 help() {
-    echo "Usage: ln-dot <dotfile> [--to-home] [--to-config] [--custom-dir <path>]" >&2
+  echo "Usage: symlink <dotfile> [--to-home] [--to-config] [--custom-dir <path>]" >&2
 }
 
 if [ $# -lt 1 ]; then
@@ -15,31 +19,31 @@ PARSED=$(getopt -o '' --long to-home,to-config,custom-dir: -- "$@")
 if [[ $? -ne 0 ]]; then
   exit 1
 fi
-eval set -- "$PARSED" 
+eval set -- "$PARSED"
 
 target_dir=""
 while true; do
   case "$1" in
-    --to-home)
-      target_dir="$HOME"
-      shift
-      ;;
-    --to-config)
-      target_dir="$HOME/.config"
-      shift
-      ;;
-    --custom-dir)
-      target_dir="$2"
-      shift 2
-      ;;
-    --)
-      shift # End of options
-      break
-      ;;
-    *)
-      echo "Invalid option: $1" >&2
-      exit 1
-      ;;
+  --to-home)
+    target_dir="$HOME"
+    shift
+    ;;
+  --to-config)
+    target_dir="$HOME/.config"
+    shift
+    ;;
+  --custom-dir)
+    target_dir="$2"
+    shift 2
+    ;;
+  --)
+    shift # End of options
+    break
+    ;;
+  *)
+    echo "Invalid option: $1" >&2
+    exit 1
+    ;;
   esac
 done
 
@@ -52,24 +56,24 @@ fi
 target="$target_dir/$(basename $source)"
 
 if [ -L "${target}" ]; then
-    # is a symlink
-    rm ${target}
-    ln -s ${source} ${target}
-    echo ":: Existing symlink ${target} removed."
-    echo ":: Symlink ${source} -> ${target} created."
+  # is a symlink
+  rm ${target}
+  ln -s ${source} ${target}
+  echo ":: Existing symlink ${target} removed."
+  echo ":: Symlink ${source} -> ${target} created."
 elif [ -d ${target} ]; then
-    # is a dir
-    rm -rf ${target}/
-    ln -s ${source} ${target}
-    echo ":: Existing directory ${target} removed."
-    echo ":: Symlink ${source} -> ${target} created."
+  # is a dir
+  rm -rf ${target}/
+  ln -s ${source} ${target}
+  echo ":: Existing directory ${target} removed."
+  echo ":: Symlink ${source} -> ${target} created."
 elif [ -f ${target} ]; then
-    # is a file
-    rm ${target}
-    ln -s ${source} ${target}
-    echo ":: Existing file ${target} removed."
-    echo ":: Symlink ${source} -> ${target} created."
+  # is a file
+  rm ${target}
+  ln -s ${source} ${target}
+  echo ":: Existing file ${target} removed."
+  echo ":: Symlink ${source} -> ${target} created."
 else
-    ln -s ${source} ${target}
-    echo ":: New symlink ${source} -> ${target} created."
+  ln -s ${source} ${target}
+  echo ":: New symlink ${source} -> ${target} created."
 fi
diff --git a/sync-pictures b/sync-pictures
--- a/sync-pictures
+++ b/sync-pictures
@@ -1,8 +1,17 @@
 #!/bin/bash
+# ---------------------------------------------------------------------------- #
+#    Script made by hengtseChou
+#    An rclone wrapper to sync ~/Pictures go Google Drive
+# ---------------------------------------------------------------------------- #
 set -e
 
 BLUE='\e[94m'
 NC='\e[0m'
+
+if ! command -v rclone 2>&1 >/dev/null; then
+    echo "Error: rclone is not installed."
+    exit 1
+fi
 
 if [ "$1" == "push" ]; then
     echo -en ":: Overwriting ${BLUE}**remote**${NC} storage. Proceed? (Y/n)"
@@ -14,7 +23,7 @@ if [ "$1" == "push" ]; then
         echo ":: Syncing canceled."
         exit 0
     fi
-elif [ "$1" == "pull" ]; then 
+elif [ "$1" == "pull" ]; then
     echo -en ":: Overwriting ${BLUE}**local**${NC} storage. Proceed? (Y/n)"
     read -e -r response
     response=${response:-y}
@@ -28,4 +37,3 @@ else
     echo "Usage: $0 {push|pull}"
     exit 1
 fi
-
diff --git a/translate b/translate
--- a/translate
+++ b/translate
@@ -1,31 +1,36 @@
 #!/bin/bash
+# ---------------------------------------------------------------------------- #
+#    Script made by hengtseChou
+#    Utilize OpenAI API to translate
+#    Support zh-tw to en, en to zh-tw
+# ---------------------------------------------------------------------------- #
 _convert_to_single_line() {
-    local raw_input="$1"
-    local single_line="${raw_input//$'\n'/\\n}"
-    echo "$single_line"
+  local raw_input="$1"
+  local single_line="${raw_input//$'\n'/\\n}"
+  echo "$single_line"
 }
 
 if [ ! -f $HOME/bin/.translate-api-key ]; then
-	echo "Error: .translate-api-key not found."
-	exit 1
+  echo "Error: .translate-api-key not found."
+  exit 1
 else
-	api_key=$(cat $HOME/bin/.translate-api-key)
+  api_key=$(cat $HOME/bin/.translate-api-key)
 fi
 
 if [ "$1" == "--to-en" ]; then
-	prompt="I want you to act as an English translator, spelling corrector and improver. I will speak to you in any language and you will detect the language, translate it and answer in the corrected and improved version of my text, in English. I want you to replace my simplified A0-level words and sentences with more beautiful and elegant, upper level English words and sentences. Keep the meaning same, but make them more literary. I want you to only reply the correction, the improvements and nothing else, do not write explanations."
+  prompt="I want you to act as an English translator, spelling corrector and improver. I will speak to you in any language and you will detect the language, translate it and answer in the corrected and improved version of my text, in English. I want you to replace my simplified A0-level words and sentences with more beautiful and elegant, upper level English words and sentences. Keep the meaning same, but make them more literary. I want you to only reply the correction, the improvements and nothing else, do not write explanations."
 elif [ "$1" == "--to-zh" ]; then
-	prompt="你是一個專業的繁體中文翻譯員。我會用任何語言傳訊息給你，請在完整的理解訊息內容後，翻譯成繁體中文，並潤飾其內容，使翻譯後的內容更加通順，但必須保持原本的意義。我希望你只回答最後的翻譯及潤飾結果，不要寫解釋，並注意不要使用簡體中文或中國用語。"
+  prompt="你是一個專業的繁體中文翻譯員。我會用任何語言傳訊息給你，請在完整的理解訊息內容後，翻譯成繁體中文，並潤飾其內容，使翻譯後的內容更加通順，但必須保持原本的意義。我希望你只回答最後的翻譯及潤飾結果，不要寫解釋，並注意不要使用簡體中文或中國用語。"
 else
-	echo "Usage: translate --to-en/--to-zh [content]"
-	exit 1
+  echo "Usage: translate --to-en/--to-zh [content]"
+  exit 1
 fi
 
 if [ -z "$2" ]; then
-    echo "Usage: translate --to-en/--to-zh [content]"
-	exit 1
+  echo "Usage: translate --to-en/--to-zh [content]"
+  exit 1
 else
-    content=$(_convert_to_single_line "$2")
+  content=$(_convert_to_single_line "$2")
 fi
 
 echo ":: Translating..."
@@ -44,5 +49,5 @@ curl -s https://api.openai.com/v1/chat/completions \
         "content": "'"$content"'"
       }
     ]
-  }' | \
+  }' |
   python3 -c "import json, sys; resp = json.load(sys.stdin); print(f'Error: {resp['error']['message']}' if 'error' in resp.keys() else resp['choices'][0]['message']['content'])"
