fix: 2&>1 (redirect stderr to stdout)

diff --git a/iPhone b/iPhone
--- a/iPhone
+++ b/iPhone
@@ -10,6 +10,11 @@ _usage() {
   echo "  -u: unmount iPhone"
 }
 
+if ! command -v ifuse 2>&1 /dev/null; then
+  echo "Error: ifuse is required."
+  exit 1
+fi
+
 operation=$1
 if [ $# -eq 0 ]; then
   _usage
