style: message output styling

diff --git a/iPhone b/iPhone
--- a/iPhone
+++ b/iPhone
@@ -11,8 +11,8 @@ _usage() {
   echo "  -h, --help: show this help message"
 }
 
-if ! command -v ifuse >/dev/null 2>&1; then
-  echo "Error: ifuse is required."
+if ! pacman -Qi ifuse &>/dev/null 2>&1; then
+  echo "[ERROR] ifuse is not installed"
   exit 1
 fi
 
@@ -25,17 +25,17 @@ if [ $operation == "-m" ]; then
   mkdir -p ~/iPhone
   ifuse ~/iPhone
   if [ $? -eq 0 ]; then
-    echo "Mounted at ~/iPhone!"
+    echo "[INFO] Mounted at ~/iPhone!"
   fi
 elif [ $operation == "-u" ]; then
   if [ ! -d ~/iPhone ]; then
-    echo "~/iPhone does not exist."
+    echo "[ERROR] ~/iPhone does not exist"
     exit 1
   else
     umount ~/iPhone
     if [ $? -eq 0 ]; then
       rm -rf ~/iPhone
-      echo "Unmounted!"
+      echo "[INFO] Unmounted!"
     fi
   fi
 elif [ $operation == "-h" ] || [ $operation == "--help" ]; then
diff --git a/lc-daily b/lc-daily
--- a/lc-daily
+++ b/lc-daily
@@ -7,23 +7,29 @@
 solution_dir="$HOME/GitHub/LeetCode"
 mkdir -p $solution_dir
 
-for cmd in docker jq nano curl; do
-  if ! command -v $cmd 2>&1 >/dev/null; then
-    echo "Error: $cmd is not installed."
-    exit 1
+deps=("docker" "jq" "nano" "curl")
+missing_deps=()
+for dep in "${deps[@]}"; do
+  if ! pacman -Qi "$dep" &>/dev/null; then
+    missing_deps+=("$dep")
   fi
 done
+if [ ${#missing_deps[@]} -ne 0 ]; then
+  echo "[ERROR] Missing dependencies: ${missing_deps[*]}"
+  exit 1
+fi
+
 if ! docker container ls -a --format '{{.Names}}' | grep -q '^alfa-leetcode-api$'; then
   docker container create --name alfa-leetcode-api -p 3000:3000 alfaarghya/alfa-leetcode-api:2.0.1
 fi
-echo "Starting alfa-leetcode-api server..."
+echo "[INFO] Starting alfa-leetcode-api server..."
 docker start alfa-leetcode-api >/dev/null
 
-echo "Fetching data from http://localhost:3000/daily..."
+echo "[INFO] Fetching data from http://localhost:3000/daily..."
 
 daily=$(curl -s --retry 10 --retry-all-errors --retry-delay 1 http://localhost:3000/daily)
 if [ $? -ne 0 ]; then
-  echo "Error: Failed to fetch data from http://localhost:3000/daily"
+  echo "[ERROR] Failed to fetch data from http://localhost:3000/daily"
   docker stop alfa-leetcode-api >/dev/null
   exit 1
 fi
@@ -33,19 +39,19 @@ questionFrontendId=$(echo "$daily" | jq -r '.questionFrontendId')
 questionFrontendId=$(printf "%04d" $questionFrontendId)
 filename="$questionFrontendId-$titleSlug"
 
-echo "Completed. Shutting down alfa-leetcode-api server..."
+echo "[INFO] Completed. Shutting down alfa-leetcode-api server..."
 docker stop alfa-leetcode-api >/dev/null
 
 cd "$solution_dir/daily"
 if [ -e "$filename.py" ]; then
-  echo "The file "$filename.py" already existed. Exiting"
+  echo "[ERROR] The file "$filename.py" already existed. Exiting"
   exit 1
 fi
 touch "$filename.py"
 nano "$filename.py"
 
 if [ ! -s "$filename.py" ]; then
-  echo "The file $filename.py is empty. Removing"
+  echo "[ERROR] The file $filename.py is empty. Removing"
   rm "$filename.py"
   exit 1
 fi
diff --git a/lc-new b/lc-new
--- a/lc-new
+++ b/lc-new
@@ -19,23 +19,23 @@ fi
 
 for cmd in jq nano curl; do
   if ! command -v $cmd 2>&1 >/dev/null; then
-    echo "Error: $cmd is not installed."
+    echo "[ERROR] $cmd is not installed."
     exit 1
   fi
 done
 
 if [ "$1" == "--refresh" ]; then
-  echo ":: Refreshing problem set..."
+  echo "[INFO] Refreshing problem set..."
   curl -s -o "$file" "$source"
 
   if [ $? -eq 0 ]; then # checks the exit status of the last executed command
     if command -v prettier 2>&1 >/dev/null; then
       prettier $file --log-level silent -w
     fi
-    echo ":: Succeeded."
+    echo "[INFO] Succeeded."
     exit 0
   else
-    echo ":: Failed to download the JSON file."
+    echo "[ERROR] Failed to download the JSON file."
     exit 1
   fi
 fi
@@ -46,7 +46,7 @@ if [ -z "$1" ]; then
 fi
 
 if [ ! -f "$file" ]; then
-  echo ":: File $file not found. You can refresh it using --refresh."
+  echo "[ERROR] File $file not found. You can refresh it using --refresh."
   exit 1
 fi
 
@@ -57,14 +57,15 @@ question_id=$(printf "%04d" $question_id)
 new_py_file="$PWD/$question_id-$title_slug.py"
 
 if [ "$titleSlug" == "null" ]; then
-  echo ":: Question ID $question_id not found."
+  echo "[ERROR] Question ID $question_id not found."
+  exit 1
 else
   touch "$new_py_file"
   nano "$new_py_file"
   if command -v black 2>&1 >/dev/null; then
-    echo ":: Running black formatter on the following files:"
-    echo "   - $new_py_file"
+    echo "[INFO] Running black formatter on the following files:"
+    echo "       - $new_py_file"
     black "$new_py_file" -l 100 -q
-    echo ":: Black formatting applied."
+    echo "[INFO] Black formatting applied."
   fi
 fi
diff --git a/pyclean b/pyclean
--- a/pyclean
+++ b/pyclean
@@ -4,8 +4,8 @@
 #    Clean up __pycache__ directories and .python_history files
 #    Recursively from the current directory
 # ---------------------------------------------------------------------------- #
-if ! command -v fd 2>&1 >/dev/null; then
-  echo "Error: fd is not installed."
+if ! pacman -Qi fd 2>&1 >/dev/null; then
+  echo "[ERROR] fd is not installed"
   exit 1
 fi
 
@@ -17,24 +17,24 @@ fi
 pycache_dirs=$(fd -H --type d "__pycache__" --exclude=".pyenv" --exclude="pipx" --exclude="Trash" --exclude=".venv" --exclude=".vscode")
 python_history_files=$(fd -H --type f "python_history" --exclude="Trash")
 if [ -z "$pycache_dirs" ] && [ -z "$python_history_files" ]; then
-  echo "No __pycache__ directories or .python_history files found."
+  echo "[INFO] No __pycache__ directories or .python_history files found"
   exit 0
 fi
 if [ -n "$pycache_dirs" ]; then
-  echo "The following __pycache__ directories were found:"
+  echo "[INFO] The following __pycache__ directories were found:"
   while IFS= read -r dir; do
-    echo "  - $PWD/$dir"
+    echo "        - $PWD/$dir"
   done <<<"$pycache_dirs"
 else
-  echo "No __pycache__ directories found."
+  echo "[INFO] No __pycache__ directories found"
 fi
 if [ -n "$python_history_files" ]; then
-  echo "The following .python_history files were found:"
+  echo "[INFO] The following .python_history files were found:"
   while IFS= read -r file; do
-    echo "  - $PWD/$file"
+    echo "        - $PWD/$file"
   done <<<"$python_history_files"
 else
-  echo "No .python_history files found."
+  echo "[INFO] No .python_history files found"
 fi
 
 read -p "Do you want to delete all of these directories and files? (yes/no) [yes]: " confirm
@@ -45,15 +45,15 @@ if [ "$confirm" == "yes" ]; then
     echo "$pycache_dirs" | while read -r dir; do
       if $use_trash; then
         if trash "$dir"; then
-          echo "Deleted: $dir"
+          echo "[INFO] Deleted: $PWD/$dir"
         else
-          echo "Failed to delete: $dir"
+          echo "[ERROR] Failed to delete: $PWD/$dir"
         fi
       else
         if rm -rf "$dir"; then
-          echo "Removed: $dir"
+          echo "[INFO] Removed: $PWD/$dir"
         else
-          echo "Failed to reomve: $dir"
+          echo "[ERROR] Failed to reomve: $PWD/$dir"
         fi
       fi
     done
@@ -62,19 +62,19 @@ if [ "$confirm" == "yes" ]; then
     echo "$python_history_files" | while read -r file; do
       if $use_trash; then
         if trash "$file"; then
-          echo "Deleted: $file"
+          echo "[INFO] Deleted: $PWD/$file"
         else
-          echo "Failed to delete: $file"
+          echo "[ERROR] Failed to delete: $PWD/$file"
         fi
       else
         if rm -f "$file"; then
-          echo "Removed: $file"
+          echo "[INFO] Removed: $PWD/$file"
         else
-          echo "Failed to remove: $file"
+          echo "[ERROR] Failed to remove: $PWD/$file"
         fi
       fi
     done
   fi
 else
-  echo "Deletion aborted."
+  echo "[INFO] Deletion aborted"
 fi
diff --git a/symlink b/symlink
--- a/symlink
+++ b/symlink
@@ -37,7 +37,7 @@ while true; do
     target_dir="$2"
     shift 2
     ;;
-  -v|--verbose)
+  -v | --verbose)
     verbose=1
     shift
     ;;
@@ -46,7 +46,7 @@ while true; do
     break
     ;;
   *)
-    echo "Invalid option: $1" >&2
+    echo "[ERROR] Invalid option: $1" >&2
     exit 1
     ;;
   esac
@@ -65,8 +65,8 @@ if [ -L "${target}" ]; then
   rm ${target}
   ln -s ${source} ${target}
   if [ $? -eq 0 ]; then
-    [ $verbose -eq 1 ] && echo ":: Existing symlink ${target} removed."
-    [ $verbose -eq 1 ] && echo ":: Symlink ${source} -> ${target} created."
+    [ $verbose -eq 1 ] && echo "[INFO] Existing symlink ${target} removed."
+    [ $verbose -eq 1 ] && echo "[INFO] Symlink ${source} -> ${target} created."
   else
     exit 1
   fi
@@ -75,8 +75,8 @@ elif [ -d ${target} ]; then
   rm -rf ${target}/
   ln -s ${source} ${target}
   if [ $? -eq 0 ]; then
-    [ $verbose -eq 1 ] && echo ":: Existing directory ${target} removed."
-    [ $verbose -eq 1 ] && echo ":: Symlink ${source} -> ${target} created."
+    [ $verbose -eq 1 ] && echo "[INFO] Existing directory ${target} removed."
+    [ $verbose -eq 1 ] && echo "[INFO] Symlink ${source} -> ${target} created."
   else
     exit 1
   fi
@@ -85,15 +85,15 @@ elif [ -f ${target} ]; then
   rm ${target}
   ln -s ${source} ${target}
   if [ $? -eq 0 ]; then
-    [ $verbose -eq 1 ] && echo ":: Existing file ${target} removed."
-    [ $verbose -eq 1 ] && echo ":: Symlink ${source} -> ${target} created."
+    [ $verbose -eq 1 ] && echo "[INFO] Existing file ${target} removed."
+    [ $verbose -eq 1 ] && echo "[INFO] Symlink ${source} -> ${target} created."
   else
     exit 1
   fi
 else
   ln -s ${source} ${target}
   if [ $? -eq 0 ]; then
-    [ $verbose -eq 1 ] && echo ":: New symlink ${source} -> ${target} created."
+    [ $verbose -eq 1 ] && echo "[INFO] New symlink ${source} -> ${target} created."
   else
     exit 1
   fi
diff --git a/sync-stat b/sync-stat
--- a/sync-stat
+++ b/sync-stat
@@ -7,31 +7,31 @@ BLUE='\e[94m'
 NC='\e[0m'
 
 if ! command -v rclone 2>&1 >/dev/null; then
-    echo "Error: rclone is not installed."
-    exit 1
+  echo "[ERROR] rclone is not installed."
+  exit 1
 fi
 
 if [ "$1" == "push" ]; then
-    echo -en ":: Overwriting ${BLUE}**remote**${NC} storage. Proceed? (Y/n): "
-    read -e -r response
-    response=${response:-y}
-    if [[ "$response" == "y" ]]; then
-        rclone sync ~/Stat/ gdrive:Stat/ --transfers 32 --checkers 64 -P --exclude=".git/" --exclude=".venv/" --exclude="__pycache__/"
-    else
-        echo ":: Syncing canceled."
-        exit 0
-    fi
+  echo -en "[INFO] Overwriting ${BLUE}**remote**${NC} storage. Proceed? (Y/n): "
+  read -e -r response
+  response=${response:-y}
+  if [[ "$response" == "y" ]]; then
+    rclone sync ~/Stat/ gdrive:Stat/ --transfers 32 --checkers 64 -P --exclude=".git/" --exclude=".venv/" --exclude="__pycache__/"
+  else
+    echo "[INFO] Syncing canceled."
+    exit 0
+  fi
 elif [ "$1" == "pull" ]; then
-    echo -en ":: Overwriting ${BLUE}**local**${NC} storage. Proceed? (Y/n): "
-    read -e -r response
-    response=${response:-y}
-    if [[ "$response" == "y" ]]; then
-        rclone sync gdrive:Stat/ ~/Stat/ --transfers 32 --checkers 64 -P
-    else
-        echo ":: Syncing canceled."
-        exit 0
-    fi
+  echo -en "[INFO] Overwriting ${BLUE}**local**${NC} storage. Proceed? (Y/n): "
+  read -e -r response
+  response=${response:-y}
+  if [[ "$response" == "y" ]]; then
+    rclone sync gdrive:Stat/ ~/Stat/ --transfers 32 --checkers 64 -P
+  else
+    echo "[INFO] Syncing canceled."
+    exit 0
+  fi
 else
-    echo "Usage: $0 {push|pull}"
-    exit 1
+  echo "Usage: $0 {push|pull}"
+  exit 1
 fi
